-- Migration 0071: Retire the period-close concept in the Workflow Guide.
-- Bank reconciliation is the real monthly close — repoint the Month-End
-- Close and Year-End "verify periods" cards at /reconciliations, and
-- deactivate the "Open New Period" card (periods are now generated by
-- /accounting-periods automatically).

BEGIN TRANSACTION;

-- Monthly Cycle > Month-End Close > "Close Period" → "Verify Reconciliation"
UPDATE workflow_cards
   SET title       = 'Verify Reconciliation',
       href        = '/reconciliations',
       description = 'Confirm the monthly bank reconciliation is complete — this is your real monthly close.'
 WHERE id = 132;

-- Year-End > Wrap Up > "Verify All Periods" → "Verify Year Reconciled"
UPDATE workflow_cards
   SET title       = 'Verify Year Reconciled',
       href        = '/reconciliations',
       description = 'Confirm all 12 monthly bank reconciliations are complete for the closing year.'
 WHERE id = 302;

-- Year-End > Open New Year > "Open New Period" — deactivate.
-- Periods are generated by /accounting-periods automatically; manually
-- opening one is no longer a workflow step.
UPDATE workflow_cards
   SET is_active = 0
 WHERE id = 320;

COMMIT;
